!!python/object:config.object_schemater_impl.SchematerModel
objects:
  SimpleCSVParser: !!python/object:config.object_schemater_impl.SchematerObjectModel
    base: BaseParser
    fields:
      args: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as args
        type: _empty
      kwargs: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as kwargs
        type: _empty
  XMLElementParser: !!python/object:config.object_schemater_impl.SchematerObjectModel
    base: BaseParser
    fields:
      args: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as args
        type: _empty
      kwargs: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as kwargs
        type: _empty
  CSVParser: !!python/object:config.object_schemater_impl.SchematerObjectModel
    base: BaseParser
    fields:
      args: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as args
        type: _empty
      kwargs: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as kwargs
        type: _empty
  ExcelCSVParser: !!python/object:config.object_schemater_impl.SchematerObjectModel
    base: BaseParser
    fields:
      args: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as args
        type: _empty
      kwargs: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as kwargs
        type: _empty
  PatternBasedLinedParser: !!python/object:config.object_schemater_impl.SchematerObjectModel
    base: BaseParser
    fields:
      args: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as args
        type: _empty
      kwargs: !!python/object:config.value_obtainers_impls.SimpleValuePrompter
        prompt_text: Specify value of type _empty as kwargs
        type: _empty
